#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <time.h>


using namespace std;

void innepodejscie(string slowo);
void optimized(string slowo);


int main(){
    clock_t start, stop;
    string slowo = "JFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHggggggggggggggFKJLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSHFKJSggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgggggggggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAggggggggggggggggggggggggggADHFLKJADSHFggggggggggggggggggggggggJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJJFSKAHFAJSDHFKJLADSHFKJSADHFLKJADSHFJKASHLFHDSAKLJJKLHKJLHJHHHHHHHHHDDDDDDDDSHGJKSDHGKJFDSHGJKDFSHGKJFDSHGKLJDFSHGJKDFSHGKJSDFHGLJKDFSHLGKJHFDSKJLGHDFSKJLGHDFSKJLGHDFSJKLGHFSDKJLHGFSDKJHGSDFKLHGDFJLSKHGKJDFSHGLJKDFSHGJKDFSLHGKLJFDSHGLKJFDSHGLKJFSDHGLKJSDFHLJKGSHDFLJKGHSDFLKGHJKHKHJKHJ";
    double czas;
    start = clock();
    for(int i = 0; i< 10000; i++)
        innepodejscie(slowo);
    stop = clock();

    czas = (double)(stop - start)/ CLOCKS_PER_SEC;

    cout<<"Inne podejscie: "<< czas <<endl<<endl;

    start = clock();
    for(int i = 0; i< 10000; i++)
        optimized(slowo);
    stop = clock();

    czas = (double)(stop - start)/ CLOCKS_PER_SEC;
    cout<<endl<<"optimized: "<< czas <<endl;




    return 0;
}


void innepodejscie(string slowo){
    char aktualny_znak = slowo[0];
    string wynik = "";
        
        int ile = 1;
        int iterator = 1;
    while(iterator <= slowo.length()){
        for(int i = iterator; i<=slowo.length() && slowo[i] == aktualny_znak; i++ ){
            ile++;
            }

        if(ile == 1){
            wynik += aktualny_znak;
        }else if(ile == 2){
            wynik += aktualny_znak;
            wynik += aktualny_znak;
        }else{
            wynik += aktualny_znak;
            wynik += to_string(ile);
        }

        iterator += ile;
        aktualny_znak = slowo[iterator-1];
        ile = 1;
    }
    //cout<< wynik<<endl;



}


void optimized(string slowo){
 string slowo_skrocone = "";
        int licznik = 1;
        
                if(slowo.length() > 1){
                        for(int i =1; i<slowo.length(); ++i){
                            if(slowo[i] == slowo[i-1]){licznik++;}

                            else if(licznik >2){
                                slowo_skrocone += slowo[i-1];
                                slowo_skrocone += to_string(licznik);
                                licznik = 1;
                            }else if(licznik == 2){
                            slowo_skrocone += slowo[i-1];
                            slowo_skrocone += slowo[i-1];
                            licznik = 1;
                           }else{
                            slowo_skrocone += slowo[i-1];
                           }

                           if(i == slowo.length()-1){
                                    if(licznik >2){
                                        slowo_skrocone += slowo[i-1];
                                        slowo_skrocone += to_string(licznik);
                                    } else if(licznik == 2){
                                        slowo_skrocone += slowo[i-1];
                                        slowo_skrocone += slowo[i-1];
                                    }else slowo_skrocone += slowo[i];
                           }
                           
                        }
                }
    else{
   // cout<< slowo_skrocone<<endl;
    }
    //cout<< slowo_skrocone<<endl;  
}